Fixed an error reading drush commands. Added command to check if drush is installed. Renamed modules and commands files

diff --git a/dwiz b/dwiz
--- a/dwiz
+++ b/dwiz
@@ -1,5 +1,9 @@
 #!/bin/bash
 clear
+
+#check if drush is installed, otherwise exit.
+command -v drush >/dev/null 2>&1 || { echo "I require foo drush it's not installed.  Aborting." >&2; exit 1;  }
+
 startdir=$(pwd)
 sdir=$(dirname "$0")
 sdir=${sdir#*/}
@@ -209,7 +213,7 @@ fi
 if [[ -z "$sub_path" ]]; then
     sub_path="public"
     read -r -p "Enter the web server relative sub path where drupal will be installed [$sub_path]: " subPath
-    [[ $subPath = '' ]] && sub_path="$subPath" || sub_path="$subPath"
+    [[ $subPath = '' ]] && sub_path="$sub_path" || sub_path="$subPath"
     echo
 fi
 
@@ -300,7 +304,7 @@ completeInstallPath="${install_path}/${sub_path}"
 
 
 #echo "The script is located at: ${startdir}"
-workingdir=$(echo $completeInstallPath)
+#workingdir=$(echo $completeInstallPath)
 #echo "The working directory is: $workingdir"
 
 module_file=$m
@@ -367,7 +371,7 @@ echo "....."
 drush dl -y drupal-"${version}" --destination="${install_path}" --drupal-project-rename="${sub_path}"
 echo
 echo
-echo "Latest Drupal ${version} release has been downloaded at " ${completeInstallPath}
+echo "Latest Drupal ${version} release has been downloaded at ${completeInstallPath}"
 echo
 echo
 
@@ -408,14 +412,14 @@ if [ $c ]; then
   echo "Performing post installation commands.."
   echo
 
-  while IFS=$'\n': read -r action
+  while IFS=$'\n': read action
     do
     case $action in \#*) continue ;; esac
 
     if [[ $action ]]; then
       echo
       echo "drush is performing [drush $action]"
-      drush "$action"
+      drush $action
     fi
   done < "$commands_file"
 fi
